const actesData = [
  {
    "id": 1,
    "titol": "REPIC DE CAMPANES per anunciar la festa",
    "lloc": "Plaça de l'Església",
    "diaKey": "divendres_18",
    "diaNom": "Divendres 18 de Setembre",
    "dataIso": "2026-09-18",
    "horaInici": "20:15",
    "horaFi": "20:25",
    "categoria": "Inici Festa",
    "icona": "fa-bell",
    "color": "#e6bd04",
    "lat": 41.413287,
    "lng": 2.017417,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Inici oficial de la Festa Major de Sant Miquel amb el repic de campanes."
  },
  {
    "id": 2,
    "titol": "Cercavila per anar a buscar els Miquels",
    "lloc": "Plaça de Catalunya",
    "diaKey": "divendres_18",
    "diaNom": "Divendres 18 de Setembre",
    "dataIso": "2026-09-18",
    "horaInici": "20:15",
    "horaFi": "21:00",
    "categoria": "Tradició",
    "icona": "fa-shoe-prints",
    "color": "#e6bd04",
    "lat": 41.413976,
    "lng": 2.015931,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": ""
  },
  {
    "id": 3,
    "titol": "Crida a la Festa Major",
     "lloc": "Plaça de Catalunya",
    "diaKey": "divendres_18",
    "diaNom": "Divendres 18 de Setembre",
    "dataIso": "2026-09-18",
    "horaInici": "21:00",
    "horaFi": "22:30",
    "categoria": "Tradició",
    "icona": "fa-fire",
    "color": "#ed0ca6",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Ajuntament de Molins de Rei",
    "fuego": true, "ruido": true, "aglom": true, "acc": false, "familia": true, "infantil": false,
    "img": "https://i.ibb.co/3YGQsLsb/image.png",
    "desc": "La benvinguda a la Festa Major de la manera més especial i que ja és tot un referent del programa d’activitats. Amb la col·laboració i participació de: Els Miquels, Dimonis, Diables de l’Agrupa, Cuc, Entxuscat, Amics del Camell, Colla Gegantera, Esbart Dansaire, Grallers, Matossers, Esventades",
  },
  {
    "id": 4,
    "titol": "Festa Major al Foment -  MIKI DKAI",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "divendres_18",
    "diaNom": "Divendres 18 de Setembre",
    "dataIso": "2026-09-18",
    "horaInici": "21:00",
    "horaFi": "22:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Reconegut monologuista gadità que ha deixat marca al món de l’humor amb el seu estil únic i el seu enginy inigualable.",
    "entrades": "https://www.giglon.com/todos?idEvent=miki-dkai-en-molins-de-rei-hoy-se-lia&directPurchase=true",
  },
   {
    "id": 5,
    "titol": "Sardaxou Electrònic",
   "lloc": "Plaça de Catalunya",
    "diaKey": "divendres_18",
    "diaNom": "Divendres 18 de Setembre",
    "dataIso": "2026-09-18",
    "horaInici": "21:30",
    "categoria": "Festa",
    "icona": "fa-music",
    "color": "#ed0ca6",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Agrupació Folklòrica Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Taller de sardanes. Actuarà la Cobla Contemporània amb el seu SARDAXOU ELECTRÒNIC, cançons actuals en versió sardanes. En acabar, un DJ."
  },
  {
    "id": 6,
    "titol": "Activitat Familiar al Museu del Renaixement",
   "lloc": "Museu del Renaixement",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Museu",
    "icona": "fa-building-columns",
    "color": "#ae560e",
   "lat": 41.412522226165244,
    "lng": 2.0168815964127487,
    "org": "Museu del Renaixement",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "Al llarg del matí convidem les famílies a participar en la creació del gran tapís-mural de la Remolina, una obra col·laborativa que quedarà exposada al vestíbul del Museu durant tota la Festa Major. Activitat gratuïta i oberta a tothom. No cal fer reserva prèvia. Si no podeu venir el dia de l’activitat, durant tota la Festa Major podreu passar per l’Oficina de Turisme, on us explicaran com podeu participar i ajudar-nos a completar el tapís."
  },
  {
    "id": 7,
    "titol": "El Cuc surt de marxa",
   "lloc": "Plaça de l’U d’Octubre de 2017",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Cultura",
    "icona": "fa-child",
    "color": "#e6bd04",
   "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Grup del Drac de Molins de Rei el Cuc",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Cada any, la gent del Cuc ens sorprèn amb les seves activitats per als més menuts. Ves a passar un bon matí amb ells!"
  },
  {
    "id": 8,
    "titol": "Diable per un dia",
   "lloc": "Plaça de l’U d’Octubre de 2017",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Cultura",
    "icona": "fa-child",
    "color": "#e6bd04",
   "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Colla Infantil de Diables de Molins de rei l’Agrupa",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Al taller de Diable per un dia els petits podran pintar la seva forca, mocadors i rajoles"
  },
  {
    "id": 9,
    "titol": "Engresca't amb l'Enxuscat",
   "lloc": "Plaça de l’U d’Octubre de 2017",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Cultura",
    "icona": "fa-child",
    "color": "#e6bd04",
   "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Grup de Foc Festinamus l’Entxuscat",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Vine a gaudir i forma part de la colla de l’Entxuscat! Encén la teva espurna, pinta cares i descobreix un munt de sorpreses més. Viu la màgia del foc, la festa i la creativitat amb nosaltres! No t’ho perdis!"
  },
  {
    "id": 10,
    "titol": "Tallers Demonícacs",
   "lloc": "Plaça de l’U d’Octubre de 2017",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Cultura",
    "icona": "fa-child",
    "color": "#e6bd04",
   "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Colla de Dimonis de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Si voleu fer de Dimoni o portar els Dracs de Molins de Rei (Llum, Foc i Tro), o pintar els Dracs i fer-vos màscares, us esperem als nostres tallers. Veniu! Ens ho passarem molt bé!"
  },
  {
    "id": 11,
    "titol": "Desperta El Camell!",
   "lloc": "Pati de Ca n'Ametller",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:00",
    "horaFi": "13:30",
    "categoria": "Amics del Camell",
    "icona": "fa-solid fa-alarm-clock",
    "color": "#ffac05",
   "lat": 41.414164,
    "lng": 2.016544,
    "org": "Amics del Camell",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Matí d’activitats per a infants i famílies amb el Camell com a protagonista. Els més menuts podran despertar la bèstia abans no arribi la Festa Major de Sant Miquel!"
  },
  {
    "id": 12,
    "titol": "Juguem a Roundnet",
   "lloc": "Pati de l'escola El Palau",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "10:30",
    "horaFi": "13:00",
    "categoria": "Alternatiu",
    "categoria": "+16",
    "icona": "fa-bowling-ball",
    "color": "#68cc20",
   "lat": 41.411572,
    "lng": 2.016433,
    "org": "Club Roundnet Molins",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Trobada a Molins de Rei per jugar a Roundnet un nou esport del municipi. Per a majors de 16 anys. Es realitzaran partits de diferents nivells."
  },
   {
    "id": 13,
    "titol": "Visita Comentada al Museu del Renaixement",
   "lloc": "Museu del Renaixement",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "11:30",
    "horaFi": "13:00",
    "categoria": "Museu",
    "icona": "fa-building-columns",
    "color": "#ae560e",
   "lat": 41.412522226165244,
    "lng": 2.0168815964127487,
    "org": "Museu del Renaixement",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "La visita, d’aproximadament una hora i mitja, recorre les sales del museu descobrint la història del Palau de Requesens, l’art del Renaixement i la vida quotidiana a l’època. Activitat gratuïta. Per participar-hi, és imprescindible fer reserva prèvia a info@museudelrenaixement.cat i rebre la corresponent confirmació. Per fer la reserva, indiqueu el vostre nom, número de persones, telèfon de contacte i codi postal.",
    "rsvp": "mailto:info@museudelrenaixement.cat?subject=Visita%20Comentada%20al%20Museu%20del%20Renaixement&body=Bones%2C%0AM'agradaria%20reservar%20la%20visita%20comentada%20al%20Museu%20del%20Renaixement.%0ALes%20meves%20dades%20s%C3%B3n%3A%0ANom%3A%0AN%C3%BAmero%20de%20persones%3A%0ATel%C3%A8fon%20de%20contacte%3A%0ACodi%20Postal%3A%0A%0AEspero%20la%20vostra%20resposta%2C%0AAtentament%2C%0ANom%20i%20Cognoms",
  },
  {
    "id": 14,
    "titol": "Paraulògic",
   "lloc": "Baixos del Molí",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "12:00",
    "horaFi": "14:00",
    "categoria": "Alternatiu",
    "icona": "fa-book",
    "color": "#20cc96",
   "lat": 41.412850,
    "lng": 2.014662,
    "org": "Òmnium Cultural",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "A partir d’una sèrie de lletres proposem als participants (individualment o en parella) construir paraules d’acord a les normes del joc “Paraulògic”. Hi haurà premis."
  },
    {
    "id": 15,
    "titol": "Escalabirres 2026 - 5è aniversari del GEA Molins!",
   "lloc": "Plaça de l'Esglesia",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "16:00",
    "horaFi": "23:00",
    "categoria": "Escalabirres",
    "icona": "fa-beer-mug-empty",
    "color": "#cc3120",
   "lat": 41.413287,
    "lng": 2.017417,
    "org": "GEA Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "5a edició d’aquesta emblemàtica activitat de Festa Major. Inscriu-te i prova de superar el rècord històric de 32 caixes. Inscripcions a partir de les 16h fins límit de places. Preu: 4 euros Pal llarg!!"
  },
    {
    "id": 16,
    "titol": "Peniescalada Lliure",
   "lloc": "Plaça Merçe Rodoreda",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "16:00",
    "horaFi": "20:00",
    "categoria": "Recorregut - Carrer Balmes fins a la plaça de Mercè Rodoreda",
    "icona": "fa-person-biking",
    "color": "#20cc4e",
   "lat": 41.412984,
    "lng":2.018861,
    "org": " Teatre de La Peni i l’Etapa Reina",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Pujada individual cronometrada sobre dues o més rodes i sense motor. Activitat popular i festiva apte per a qualsevol persona, animal o cosa. Inscripció prèvia a www.teatredelapeni.cat"
  },
   {
    "id": 17,
    "titol": "Rollover Fest 2026",
   "lloc": "Skate Park - Parc del Llobregat",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "17:00",
    "horaFi": "20:00",
    "categoria": "Alternatiu",
    "icona": "fa-circle-dot",
    "color": "#20cc4e",
   "lat": 41.405840,
    "lng":2.017779,
    "org": "Club Esportiu RollOver Molins",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"2a edició del RollOver Fest. Gimcana sobre rodes gratuïta a l’Skatepark de Molins! Descobreix el patinatge en línia i coneix el nou club RollOver Molins!"
  },
   {
    "id": 18,
    "titol": "Holi Fest Holi Cuc",
   "lloc": "Parc de la Mariona",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "17:00",
    "horaFi": "20:00",
    "categoria": "Holi Fest!",
    "icona": "fa-fill",
    "color": "#e421ca",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "Grup del Drac de Molins de Rei el Cuc",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc":"Holi Cuc... i flipa en colors!"
  },
   {
    "id": 19,
    "titol": "Vespreig - XX Aniversari Move Your Fucking Brain",
   "lloc": "Pati de Ca n'Ametller",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "18:30",
    "horaFi": "22:00",
    "categoria": "Música",
    "icona": "fa-mix",
    "color": "#1c181c",
  "lat": 41.414164,
    "lng": 2.016544,
    "org": "Metal Defenders",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"Vine a gaudir i celebrar el XX aniversari del Move your fucking brain. Tarda plena de sorolls foscos, bona música, bona companyia i bon espai."
  },
  {
    "id": 20,
    "titol": "Balls amb Jaume Junior",
   "lloc": "Plaça Vicenç Fernández",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "20:30",
    "horaFi": "22:00",
    "categoria": "Balls",
    "icona": "fa-user",
    "color": "#d0ba12",
  "lat": 41.40658542916734,
    "lng": 2.019835924191904,
    "org": "Organitzador Desconegut",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":""
  },
   {
    "id": 21,
    "titol": "Cinema de Festa Major - Les Musiciens (2025)",
   "lloc": "Teatre de la Peni",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "20:00",
    "horaFi": "22:00",
    "categoria": "Cinema de Festa Major",
    "icona": "fa-clapperboard",
    "color": "#d01245",
  "lat": 41.413092825584116,
    "lng": 2.0193234420256814,
    "org": "Cine Club Hal 2002",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "https://www.cineclubhal2002.cat/wp-content/uploads/2026/08/les_musiciens-156383630-large.jpg",
    "desc":"Astrid Thompson finalment aconsegueix fer realitat el somni del seu pare: reunir quatre Stradivarius per a un concert únic i molt esperat pels amants de la música de tot el món. Però els quatre virtuosos escollits per a l’ocasió no poden tocar junts i les crisis d’ego se succeeixen a mida que avancen amb els assajos. Desesperada, Astrid decideix anar a buscar l’únic que, al seu parer, encara pot salvar el concert: Charlie Beaumont, el compositor de la banda sonora.",
    "entrades": "https://www.entrapolis.com/entrades/los-musicos-peni",
  },
  {
    "id": 22,
    "titol": "Festa Major al Foment -  Remember Show",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "21:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Un espectacle d’animació amb música variada dels anys 80, 90 i més acompanyat d’un DJ. Vine a ballar i gaudir de la música que va marcar dues dècades!"
  },
  {
    "id": 23,
    "titol": "Correfoc Infantil",
    "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "20:30",
    "categoria": "Correfoc",
    "icona": "fa-fire",
    "color": "#ff0000",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Infantil de Diables de Molins de Rei l’Agrupa, Colla Infantil Dimonis de Molins de Rei i Entxuscat de Molins de Rei",
    "fuego": true, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Ja el tornem a tenir aquí! Veniu ben protegits per gaudir de les espurnes, els tabals dels dimonis, dels diables i de les bèsties infantils de foc. Una nit plena de màgia i foc per als més valents! No hi falteu!"
  },
  {
    "id": 24,
    "titol": "Nit de Festa amb PDs 750",
    "lloc": "Pati de la Peni",
    "diaKey": "dissabte_19",
    "diaNom": "Dissabte 19 de Setembre",
    "dataIso": "2026-09-19",
    "horaInici": "23:00",
    "horaFi": "03:00",

    "categoria": "DJ i Festa",
    "icona": "fa-music",
    "color": "#ff00bf",
   "lat": 41.4128388657654,
    "lng": 2.0195345668894986,
    "org": "Joventut Catòlica – La Peni",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Música festiva i mesclada a càrrec de PDs locals"
  },
  {
    "id": 25,
    "titol": "Cursa 10KM - 47a Cursa Popular de Sant Miquel",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "08:30",
    "horaFi": "10:00",

    "categoria": "Cursa de Sant Miquel",
    "icona": "fa-person-running",
    "color": "#26e7e1",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": "Esports Molins",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "NOVETAT: Divendres 18 i dissabte 19 recollida dels dorsals a l’edifici dels Baixos del Molí. Participació oberta a tothom, tota d’informació e inscripcions: https://www.molinsderei.site/cursasantmiquel/"
  },
  {
    "id": 26,
    "titol": "Cursa 5KM Relleus per parelles - 47a Cursa Popular de Sant Miquel",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "08:30",
    "horaFi": "10:00",

    "categoria": "Cursa de Sant Miquel",
    "icona": "fa-person-running",
    "color": "#26e7e1",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": "Esports Molins",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "NOVETAT: Divendres 18 i dissabte 19 recollida dels dorsals a l’edifici dels Baixos del Molí. Participació oberta a tothom, tota d’informació e inscripcions: https://www.molinsderei.site/cursasantmiquel/"
  },
  {
    "id": 27,
    "titol": "Cursa Popular 3,5KM - 47a Cursa Popular de Sant Miquel",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "10:30",
    "horaFi": "11:00",

    "categoria": "Cursa de Sant Miquel",
    "icona": "fa-person-running",
    "color": "#26e7e1",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": "Esports Molins",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "NOVETAT: Divendres 18 i dissabte 19 recollida dels dorsals a l’edifici dels Baixos del Molí. Participació oberta a tothom, tota d’informació e inscripcions: https://www.molinsderei.site/cursasantmiquel/"
  },
  {
    "id": 28,
    "titol": "Cursa Infantil 1,5KM - 47a Cursa Popular de Sant Miquel",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "11:15",
    "horaFi": "11:45",

    "categoria": "Cursa de Sant Miquel",
    "icona": "fa-person-running",
    "color": "#26e7e1",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": "Esports Molins",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "NOVETAT: Divendres 18 i dissabte 19 recollida dels dorsals a l’edifici dels Baixos del Molí. Participació oberta a tothom, tota d’informació e inscripcions: https://www.molinsderei.site/cursasantmiquel/"
  },
  {
    "id": 29,
    "titol": "Cursa Familiar 950m - 47a Cursa Popular de Sant Miquel",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "12:00",
    "horaFi": "12:45",
    "categoria": "Cursa de Sant Miquel",
    "icona": "fa-person-running",
    "color": "#26e7e1",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": "Esports Molins",
    "fuego": false, "ruido": false, "aglom": true, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "NOVETAT: Divendres 18 i dissabte 19 recollida dels dorsals a l’edifici dels Baixos del Molí. Participació oberta a tothom, tota d’informació e inscripcions: https://www.molinsderei.site/cursasantmiquel/"
  },
  {
    "id": 30,
    "titol": "Fest(a) la paella i Jocs Rurals de l'Ateneu Mulei",
    "lloc": "Plaça de l'Església",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "11:00",
    "horaFi": "18:00",
    "categoria": "Tradició",
    "icona": "fa-dice-six",
    "color": "#e6bd04",
    "lat": 41.413287,
    "lng": 2.017417,
    "org": "Ateneu Mulei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "•11 h. Fest(A) la paella: amb equips de quatre persones, convocatòria per cuinar paelles pel dinar popular. •14 h. Dinar popular i sobretaula: dinar popular amb paella, pa i vi inclòs amb tiquet previ, després sobretaula amenitzada. •17h. Jocs rurals: equips mixtes i moltes ganes de passar-ho bé per aconseguir el premi dels jocs rurals. Tota la informació a les xarxes socials de l’Ateneu Mulei."
  },
   {
    "id": 31,
    "titol": "Diada Castellera de Festa Major",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "12:30",
    "categoria": "Tradició i Cultura",
    "icona": "fa-users-line",
    "color": "#f79900",
   "lat": 41.4120091559705,
    "lng": 2.0165777481710188,
    "org": "Colla Castellera Matossers de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Diada castellera de Festa Major, amb l’actuació dels Castellers d’Esparreguera, Castellers de Badalona, Castellers del Poble Sec i Matossers de Molins de Rei."
  },
  {
    "id": 32,
    "titol": "Festa i Foc - Inauguració Exposició",
    "lloc": "Ca n'Ametller",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "18:00",
    "categoria": "Cultura",
  "icona": "fa-building-columns",
    "color": "#ae560e",
   "lat": 41.41398470799852,
    "lng": 2.0161131574823927,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "Festa i foc són inseparables durant la Festa Major. Us proposem un recorregut visual a partir d'una selecció de diverses fotografies."
  },
  {
    "id": 33,
    "titol": "Festa Major al Foment -  Montserrat Martí Caballé",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "18:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Montserrat Martí presenta el recital d’òpera i sarsuela al costat del baríton zamorà Luis Santana acompanyats pel pianista Francesc Blanco.",
    "entrades": "https://www.entrapolis.com/entrades/montserrat-marti-caballe-recital-dopera-i-sarsuela",
  },
  {
    "id": 34,
    "titol": "Daltabaix Presenta: La Rauxa",
    "lloc": "Pati de Ca n'Ametller",
    "diaKey": "diumenge_20",
    "diaNom": "Diumenge 20 de Setembre",
    "dataIso": "2026-09-20",
    "horaInici": "19:00",
    "categoria": "Música",
    "icona": "fa-music",
    "color": "#bd029e",
    "lat": 41.414164,
    "lng": 2.016544,
    "org": "Daltabaix",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "La Rauxa són un projecte musical per retre homenatge a l’ecosistema musical dels Països Catalans dels anys 60 i 70. El repertori el conformen composicions pròpies que miren de reüll al pop, la cruesa del garatge i l’elegància del Northern Soul, tot passat pel sedàs de la música que es feia a casa nostra durant aquells anys."
  },
   {
    "id": 35,
    "titol": "Berenar amb la Remolina",
    "lloc": "Plaça del Palau",
    "diaKey": "dilluns_21",
    "diaNom": "Dilluns 21 de Setembre",
    "dataIso": "2026-09-21",
    "horaInici": "17:30",
    "categoria": "Infantil",
    "icona": "fa-child",
    "color": "#931759",
    "lat": 41.412295,
    "lng": 2.016797,
    "org": "Museu del Renaixement",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc": "Veniu al berenar amb la Remolina, una jove entremaliada que va viure al Palau de Requesens fa 500 anys i que ha esdevingut l’ambaixadora del Museu de Renaixement pels més petits! Activitat gratuïta"
  },
  {
    "id": 36,
    "titol": "Inauguració dels jardins de Joan Janés i Cogul",
    "lloc": "Plaça de l'U d'Octubre de 2017",
    "diaKey": "dilluns_21",
    "diaNom": "Dilluns 21 de Setembre",
    "dataIso": "2026-09-21",
    "horaInici": "19:00",
    "categoria": "Institucional",
    "icona": "fa-leaf",
    "color": "#17932c",
    "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Inauguració de l’espai que li dedica al municipi al Joan Janés i Cogul (1928-2023), qui fou esportista, directiu esportiu, regidor de l’Ajuntament, promotor de projectes públics, dinamitzador cultural, fotògraf i activista del moviment associatiu."
  },
   {
    "id": 37,
    "titol": "Pregó Institucional",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "dimarts_22",
    "diaNom": "Dimarts 22 de Setembre",
    "dataIso": "2026-09-22",
    "horaInici": "20:00",
    "categoria": "Institucional",
    "icona": "fa-microphone",
    "color": "#b7b106",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Pregó institucional a càrrec de Míriam Cano. Aforament limitat."
  },
  {
    "id": 38,
    "titol": "Mou-te amb One Mile",
    "lloc": "Parc de la Mariona",
    "diaKey": "dimecres_23",
    "diaNom": "Dimecres 23 de Setembre",
    "dataIso": "2026-09-23",
    "horaInici": "18:00",
    "horaFi": "19:30",
    "categoria": "Esport",
    "icona": "fa-dumbbell",
    "color": "#15c830",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "One Mile Crossfit",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Una sessió oberta a tothom per descobrir una manera diferent de moure’s i entrenar. Durant una hora combinarem exercici funcional, petits reptes i treball en equip, en un ambient divertit i de comunitat. No cal experiència prèvia! Més informació i inscripcions al web: https://onemilecrossfit.com/"
  },
  {
    "id": 39,
    "titol": "Nit Jove",
    "lloc": "Pista de la Federació Obrera",
    "diaKey": "dijous_24",
    "diaNom": "Dijous 24 de Setembre",
    "dataIso": "2026-09-24",
    "horaInici": "16:00",
    "horaFi": "22:30",
    "categoria": "Joventut",
    "icona": "fa-child-reaching",
    "color": "#01d1af",
   "lat": 41.41529697184773,
    "lng":2.018598794710063,
    "org": "Arran Molins",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Després d’uns anys de parèntesi, torna la històrica Nit Jove de la Festa Major de Molins de Rei. Xerrades, tallers, sopar popular, glosa i música com a prèvia de Sant Miquel. Construïm espais d’oci alternatiu, ens hi juguem la vila!"
  },
  {
    "id": 40,
    "titol": "Cercavila de Grallers i Bastoneres i Berenar Popular",
    "lloc": "Plaça de la Creu",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "17:30",
    "categoria": "Joventut",
    "icona": "fa-deezer",
    "color": "#abab12",
   "lat": 41.4108797093698,
    "lng":2.019015098294698,
    "org": "Grallers de Molins de Rei i Bastoneres de Molins",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Els Grallers de Molins de Rei i les Esventades, Bastoneres de Molins, ompliran de música i danses els carrers de la vila en el seu tradicional Cercavila de Grallers que culminarà amb un berenar popular."
  },
  {
    "id": 41,
    "titol": "Visita Patrimonial",
    "lloc": "Biblioteca el Molí",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "17:30",
    "horaFi": "18:30",
    "categoria": "Patrimoni",
    "icona": "fa-building-columns",
    "color": "#ae560e",
     "lat": 41.41333675323307,
    "lng":2.0146961178310985,
    "org": "Biblioteca el Molí i la Regidoria de Patrimoni",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "La Biblioteca el Molí, antiga Fàbrica Ferrer i Mora. Un recorregut guiat per conèixer la història de l’antiga fàbrica a través dels espais de la Biblioteca. Places limitades. Inscripcions a partir del 7 de setembre. La inscripció només serà vàlida un cop hagi estat confirmada per la Biblioteca el Molí",
     "rsvp": "https://www.molinsderei.site/bibliotecaelmoli/events/visita-patrimonial-la-biblioteca-el-moli-antiga-fabrica-ferrer-i-mora-34/",
  },
  {
    "id": 42,
    "titol": "Festa Major al Foment -  A solas con Alejandro Sanz",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "20:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Homenatge íntim i emocional a l’obra d’un dels artistes més influents del pop en espanyol.",
    "entrades": "https://www.sokoentradas.com/espectaculo/6/tributo-alejandro-sanz-en-molins-de-rei.html",
  },
  {
    "id": 43,
    "titol": "Correfoc de Diables i Bèsties",
    "lloc": "Plaça de Catalunya",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "21:00",
    "categoria": "Correfoc",
    "icona": "fa-fire",
    "color": "#ff0000",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Infantil de Diables de Molins de Rei l’Agrupa, Colla Infantil Dimonis de Molins de Rei i Entxuscat de Molins de Rei",
    "fuego": true, "ruido": true, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Les colles de foc de la vila i les seves colles convidades faran sonar els seus tabals pels nostres carrers. Les bèsties, els diables i els dimonis us faran córrer i saltar amb les seves guspires. Veniu preparats per gaudir d’una nit màgica de percussió i foc. No us ho perdeu!"
  },
   {
    "id": 44,
    "titol": "Los 80 Pasajeros",
    "lloc": "Parc del Llobregat",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "22:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Los 80 pasajeros és una banda que ofereix un viatge en directe pel millor pop-rock espanyol dels anys 80 i 90, amb un repertori de grans èxits que connecta amb diverses generacions. Amb una posada en escena dinàmica, fa cada concert una experiència plena d’energia, ritme i complicitat amb el públic."
  },
  {
    "id": 45,
    "titol": "Rocktambuls",
    "lloc": "Parc del Llobregat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "00:00",
    "horaFi": "01:30",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Amb prop de dues dècades d’experiència dels escenaris i amb profundes arrels a Molins de Rei, Rocktambuls és sinònim de potència, diversió i festa en estat pur. El repertori està ple de grans èxits del pop, pop-rock català i internacional, i clàssics de totes les èpoques i per a totes les edats. Preparats per sentir la Rocktambulina?"
  },
  {
    "id": 46,
    "titol": "DJ al Parc del Llobregat",
    "lloc": "Parc del Llobregat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "01:30",
    "horaFi": "04:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "HORES NO OFICIALS. HORARI POT CANVIAR - Tancament del Recinte a les 4:00"
  },
  {
    "id": 47,
    "titol": "41a Fira del Col·leccionisme i Brocanters",
    "lloc": "Passeig del Terraplè",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "09:00",
    "horaFi": "14:00",
    "categoria": "Tradició",
    "icona": "fa-camera-retro",
    "color": "#8b5305",
   "lat": 41.41116198691299,
    "lng": 2.0159850705506908,
    "org": "Associació Filatèlica i Numismàtica de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Hi podreu trobar, entre d’altres: bitllets, monedes, plaques de cava, accions, discos, llibres, pòsters, cromos, didals, cargols, eines, vintage, paper, postals, figures, etc. Trobada d’intercanvi de plaques de cava, segells, xapes,..."
  },
  {
    "id": 48,
    "titol": "1a Trobada de Vehicles Clàssics i Esportius MCMC",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "09:00",
    "horaFi": "13:00",
    "categoria": "Alternatiu",
    "icona": "fa-car-side",
    "color": "#055e8b",
    "lat": 41.412976,
    "lng": 2.014271,
    "org": "Associació Motor Club Molins Clàssics",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Trobada de vehicles clàssics i esportius a Molins de Rei."
  },
  {
    "id": 49,
    "titol": "L'art de la Imaginació",
     "lloc": "Passeig del Terraplè",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "10:30",
    "horaFi": "11:30",
    "categoria": "Art",
    "icona": "fa-palette",
    "color": "#cc007b",
   "lat": 41.41116198691299,
    "lng": 2.0159850705506908,
    "org": "Ateneu Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "A través de les activitats artístiques, posem l’interès d’aprendre i divertir-se tot pintant el que el nostre imaginari veu més enllà de la realitat. Ens acompanyaran els artistes: Meritxell Salvado (il·lustradora), Pau Gamez (dibuixant de còmic) i Cir Moriana (pintor i artista multidisciplinar)."
  },
{
    "id": 50,
    "titol": "Festa Major al Foment -  Portes Obertes",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "10:00",
    "horaFi": "13:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Coneguem el Foment per dins",
    "rsvp": "https://www.entrapolis.com/entrades/portes-obertes-del-foment",

  },
   {
    "id": 51,
    "titol": "Simultànies d'Escacs",
     "lloc": "Passeig del Terraplè",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "11:00",
    "horaFi": "12:00",
    "categoria": "Escacs",
    "icona": "fa-chess",
    "color": "#434343",
   "lat": 41.41116198691299,
    "lng": 2.0159850705506908,
    "org": "Club d’Escacs Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Simultànies d’escacs, amb la presència de Victor Vehí, mestre internacional d’escacs, campió de Catalunya absolut en els anys 1993 i 1998. Vehí compta amb una dilatada trajectòria dins dels escacs catalans."
  },
   {
    "id": 52,
    "titol": "Dona el Xumet al Camell",
     "lloc": "Plaça de l'U d'Octubre de 2017",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "11:00",
    "categoria": "Amics del Camell",
    "icona": "fa-baby",
    "color": "#ff7300",
   "lat": 41.413530046788644,
    "lng": 2.014249013840085,
    "org": "Amics del Camell",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Els més menuts de la Vila podran demostrar que s’han fet grans entregant el seu xumet Camell."
  },
  {
    "id": 53,
    "titol": "Rebuda dels Gegants Convidats",
     "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "11:00",
    "horaFi": "12:00",
    "categoria": "Cultura i Tradició",
    "icona": "fa-certificate",
    "color": "#8cd60c",
  "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Gegantera de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Recorregut: plaça Catalunya, carrer Major, plaça delMercat, carrer Rafael Casanova, Catalunya."
  },
  {
    "id": 54,
    "titol": "Ballada de Gegants",
     "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "12:00",
    "categoria": "Cultura i Tradició",
    "icona": "fa-certificate",
    "color": "#8cd60c",
  "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Gegantera de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Recorregut: plaça Catalunya, carrer Major, plaça delMercat, carrer Rafael Casanova, Catalunya."
  },
  {
    "id": 55,
    "titol": "Vermut Electrònic de Festa Major",
     "lloc": "Parc del Llobregat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "12:00",
      "horaFi": "16:00",
    "categoria": "Alternatiu",
    "icona": "fa-wine-glass",
    "color": "#ff0353",
  "lat": 41.405840,
    "lng":2.017779,
    "org": "Diables de l’AGRUPA de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc": "Tercer vermut electrònic, amb DJ en directe, moltes tapes i gran fideuada popular. Els més petits podran jugar als castells inflables instal·lats. Aquest any amb taules i cadires"
  },
  {
    "id": 56,
    "titol": "Correcuita del Petit Camell",
     "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "17:00",
    "horaFi": "17:45",
    "categoria": "Amics del Camell",
    "icona": "fa-fire",
    "color": "#ff5e00",
  "lat": 41.413976,
    "lng": 2.015931,
    "org": "Amics del Camell",
    "fuego": true, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "El Petit Camell tornarà a treure el cap pel carreró per fer el seu correcuita infantil"
  },
  {
    "id": 57,
    "titol": "Passada dels Gegants",
     "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "17:45",
    "categoria": "Cultura i Tradició",
    "icona": "fa-certificate",
    "color": "#8cd60c",
  "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Gegantera de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Un moment perfecte per poder gaudir sense presses dels Gegants arribats de fora de Catalunya. Els amfitrions de l’acte, en Miquel, la Montserrat, en Bernat i la Candelera ballaran al so de la música de MúsXXL"
  }, 
  {
    "id": 58,
    "titol": "Ritmes del Món",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "17:45",
    "categoria": "Alternatiu",
    "icona": "fa-drum",
    "color": "#8a4b04",
    "lat": 41.412976,
    "lng": 2.014271,
    "org": "Organitzador Desconegut",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Tarda d’actuacions musicals amb la participació de Grup IFSAN (grup tradicional del Marroc). IFSAN és un grup de música popular d’arrel amaziga amb una proposta que reinterpreta la tradició musical del nord d’Àfrica amb ritmes i harmonies actuals. Una música festiva i plena d’energia que trasmet valors de pau, llibertat, igualtat i solidaritat. “Elenco Folklórico Reseda Poty Paraguay”. Grup folklòric paraguaià que manté viva la tradició cultural del Paraguai a través de la música i la dansa. Una proposta plena de color, ritme i tradició. El Cor de la Dona. Grup sorgit de l’entitat el Casal de la Dona al 2016, el seu repertori inclou cançons diverses en català, castellà i italià."
  },
   {
    "id": 59,
    "titol": "Concert Flamenc",
   "lloc": "Plaça Vicenç Fernández",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "19:30",
    "horaFi": "21:00",
    "categoria": "Balls",
    "icona": "fa-guitar",
    "color": "#d0ba12",
  "lat": 41.40658542916734,
    "lng": 2.019835924191904,
    "org": "Associació de veïns El Canal",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"Dia de l’associació Barri El Canal amb un concert de flamenc, cant i ball."
  },
  {
    "id": 60,
    "titol": "Vespre Musical a la Federació Obrera",
    "lloc": "Pista de la Federació Obrera",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "19:30",
    "horaFi": "22:00",
    "categoria": "Música",
    "icona": "fa-music",
    "color": "#ff05c5",
   "lat": 41.41529697184773,
    "lng":2.018598794710063,
    "org": "Organitzador Desconegut",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": ""
  },
  {
    "id": 61,
    "titol": "Correcuita del Camell i Sarau d'Espurnes",
    "lloc": "Plaça de Catalunya",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "20:30",
    "horaFi": "00:00",
    "categoria": "Amics del Camell",
    "icona": "fa-fire",
    "color": "#ff5005",
     "lat": 41.413976,
    "lng": 2.015931,
    "org": "Amics del Camell",
    "fuego": true, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Tradicional Correcuita i Sarau d’Espurnes del Camell de Molins de Rei amb un espectacle d’inici per celebrar el 45è aniversari de la bèstia"
  },
   {
    "id": 62,
    "titol": "Nocturnal (Tribut a Amaral)",
    "lloc": "Parc del Llobregat",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "22:00",
    "horaFi": "23:30",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Arriba NOCTURNAL, el tribut a Amaral. Un recordatori de l’extensa carrera de la banda liderada per l’Eva Amaral i el Juan Aguirre, des dels seus inicis al 1998 fins a l’actualitat."
  },
  {
    "id": 63,
    "titol": "Allioli",
    "lloc": "Parc del Llobregat",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "00:00",
    "horaFi": "02:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "El grup de versions Allioli és una proposta festiva que aposta per un repertori exclusivament en català. Amb 8 músics sobre l’escenari, ofereixen dues hores de música en directe de gran qualitat, combinant energia, bon ambient i les millors cançons del nostre país."
  },
  {
    "id": 64,
    "titol": "DJ al Parc del Llobregat",
    "lloc": "Parc del Llobregat",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "02:00",
    "horaFi": "04:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Tancament del recinte a les 04:00"
  },
  {
    "id": 65,
    "titol": "39a Trobada de Gegants i Capgrossos",
    "lloc": "Plaça de Catalunya",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "09:00",
    "horaFi": "13:00",
    "categoria": "Cultura i Tradició",
    "icona": "fa-certificate",
     "color": "#e6bd04",
    "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Gegantera de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "•9 h - Plantada de gegants •11 h - Mostra de balls de gegants •11.30 h - Inici de la cercavila •13 h - Final a plaça de Catalunya"
  },
  {
    "id": 66,
    "titol": "Taller de Gospel",
    "lloc": "Federació Obrera",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "11:00",
    "horaFi": "13:00",
    "categoria": "Cant",
    "icona": "fa-microphone",
     "color": "#04e69b",
    "lat": 41.414993287772745,
    "lng": 2.0187880848093442,
    "org": "Gospel Feelings Molins",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Sents el ritme? T’agrada cantar? Aquest taller és per a tu! Obert a tothom i gratuït. Vine a gaudir de la música!!"
  }, 
  {
    "id": 67,
    "titol": "Vespreig Inclusiu Enreda't",
    "lloc": "Baccus Molins",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "17:00",
    "horaFi": "19:30",
    "categoria": "Associació Enreda't",
    "icona": "fa-music",
     "color": "#04e640",
    "lat": 41.41125266679707,
    "lng": 2.015239624490672,
    "org": "Associació Enreda’t",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Discoteca inclusiva amb DJ Jambo Jambito. Una tarda de música, ball i diversió adreçada principalment a persones amb discapacitat intel·lectual, en un espai segur, adaptat i respectuós que afavoreix la socialització i la participació. Vine a gaudir de la Festa Major amb nosaltres!"
  },
  {
    "id": 68,
    "titol": "Campionat d'Estirar la Corda",
    "lloc": "Plaça de l'Església",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "17:00",
    "horaFi": "20:00",
    "categoria": "Alternatiu",
    "icona": "fa-square",
    "color": "#e6bd04",
    "lat": 41.413287,
    "lng": 2.017417,
    "org": "Ateneu Mulei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Tradicional concurs d’estirar la corda per equips de 5 persones de totes les edats. Inscripcions i més informació a les xarxes socials de l’Ateneu Mulei."
  },
  {
    "id": 69,
    "titol": "Tardeo de l'Enxuscat",
    "lloc": "Plaça del Mercat",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "17:00",
    "horaFi": "21:00",
    "categoria": "Vespreig",
    "icona": "fa-music",
    "color": "#0493e6",
    "lat": 41.411661567317,
    "lng": 2.0173559797173923,
    "org": "Grup de Foc Festinamus Entxuscat",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": true,
    "img": "",
    "desc": "Vine a viure el tardeo de l’Entxuscat on el temps s’atura, on les preocupacions s’esvaeixen i només queda el plaer de compartir, ballar i sentir. La tarda ens espera. I tu, vindràs?"
  },
  {
    "id": 70,
    "titol": "Anna Blasco en Concert",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "17:30",
    "horaFi": "18:30",
    "categoria": "Música",
    "icona": "fa-music",
    "color": "#fb00ff",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": " Església Evangèlica de Molins",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Concert de música pop i R&B amb cançons inspirades en experiències viscudes arreu del món."
  },
  {
    "id": 71,
    "titol": "Festa Major al Foment -  ImproShow",
    "lloc": "Foment Cultural i Artístic",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "18:00",
    "categoria": "Cultura",
    "icona": "fa-masks-theater",
    "color": "#0888ac",
    "lat": 41.41168711409592,
    "lng": 2.0153204125386446,
    "org": "Foment Cultural i Artístic",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Espectacle d’humor, original i interactiu. Els actors surten a escena sense guió, i el públic decideix què passarà. Un xou diferent i únic en cada funció.",
     "rsvp": "https://www.entrapolis.com/entrades/improshow-foment-cultural-i-artistic-27092026",
  },
  {
    "id": 72,
    "titol": "Versots dels Dimonis de Molins de Rei",
    "lloc": "Plaça de la Creu",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "18:30",
    "categoria": "Cultura",
    "icona": "fa-comment",
    "color": "#ea9917",
   "lat": 41.4108797093698,
    "lng":2.019015098294698,
    "org": "Dimonis de Molins de Rei",
    "fuego": true, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Sàtira, humor, espectacle, crítica a la situació municipal i mundial. Des dels Inferns venen els Dimonis de Molins de Rei, encapçalats pel Llucifer i la Diablesa, per donar-nos la seva visió crítica amb uns versots ben punyents sobre què ens està passant. Podrà Sant Miquel evitar-ho? Veniu a gaudir-ne! La pirotècnia que s’utilitzarà a l’espectacle és de foc fred i no crema."
    },
      {
    "id": 73,
    "titol": "Esbart Dansaire - Arrels en Dansa",
    "lloc": "Plaça de la Llibertat",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "19:30",
    "horaFi": "20:30",
    "categoria": "Tradició",
    "icona": "fa-certificate",
    "color": "#bb8d10",
   "lat": 41.412976,
    "lng": 2.014271,
    "org": " Esbart Dansaire de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Espectacle d’arrel tradicional i danses de nova creació a càrrec del Cos de Dansa i les seccions de l’Escola de l’Esbart."
  },
      {
    "id": 74,
    "titol": "Nil Matamala presenta: Nature",
    "lloc": "Plaça Vicenç Fernández",
    "diaKey": "dilluns_28",
    "diaNom": "Dilluns 28 de Setembre",
    "dataIso": "2026-09-28",
    "horaInici": "19:00",
    "horaFi": "20:00",
    "categoria": "Màgia",
    "icona": "fa-wand-magic-sparkles",
    "color": "#c921b2",
  "lat": 41.40658542916734,
    "lng": 2.019835924191904,
    "org": "Nil Matamala",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "Espectacle de màgia."
  },
  {
    "id": 75,
    "titol": "Kelly Isaiah",
    "lloc": "Parc del Llobregat",
    "diaKey": "dilluns_28",
    "diaNom": "Dilluns 28 de Setembre",
    "dataIso": "2026-09-28",
    "horaInici": "22:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Després de liderar el grup Koers, Kelly Isaiah presenta l’espectacle del seu primer disc en solitari, ODARO (Cap endavant), una declaració d’identitat que connecta herència africana i present català, combinant energia rítmica i vulnerabilitat emocional en un directe pensat per a circuits professionals i festivals."
  },
  {
    "id": 76,
    "titol": "La Ludwig Band",
    "lloc": "Parc del Llobregat",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "00:00",
    "horaFi": "01:30",

    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Prolífics, virtuosos i despreocupats són els tres adjectius que millor defineixen La Ludwig Band, el grup que ha revolucionat l’escena catalana amb lletres sofisticades i una ironia lúcida. Arriben al 2026 amb el disc “Pel barri es comenta”, amb temàtica més urbana, on la ciutat té molt de pes, en contraposició de l’ambientació de les publicacions anteriors."
   },
   {
    "id": 77,
    "titol": "DJ al Parc del Llobregat",
    "lloc": "Parc del Llobregat",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "01:30",
    "horaFi": "05:00",
    "categoria": "Concerts al Parc del Llobregat",
    "icona": "fa-music",
    "color": "#ff00e6",
   "lat": 41.40580874727223,
    "lng": 2.0181858465558715,
    "org": "Cultura Molins",
    "fuego": false, "ruido": true, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Tancament del Recinte a les 05:00"
     },
     {
    "id": 78,
    "titol": "Cercavila de Pre-Matines",
    "lloc": "Plaça de Catalunya",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "05:00",
    "horaFi": "06:00",
    "categoria": "Amics del Camell",
    "icona": "fa-drum",
    "color": "#ff6a00",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Amics del Camell",
    "fuego": true, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Els Timbalers del Camell faran un recorregut circular amb timbals i traques valencianes per anunciar l’arribada de les Matines i despertar la vila amb motiu de la diada de Sant Miquel."
     },
      {
    "id": 79,
    "titol": "Matines del Camell",
    "lloc": "Plaça de Catalunya",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "06:00",
    "horaFi": "08:30",
    "categoria": "Amics del Camell",
    "icona": "fa-fire",
    "color": "#ff6a00",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Amics del Camell",
    "fuego": true, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "El Camell es lleva d’hora el dia de Sant Miquel! Segueixlo, corre amb ell o mira’l de lluny, però no t’ho perdis"
     },
      {
    "id": 80,
    "titol": "Esmorzar dels Miquels",
    "lloc": "Carrer de Sant Miquel",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "09:00",
    "categoria": "Sant Miquel",
    "icona": "fa-mug-saucer",
    "color": "#ff0073",
   "lat": 41.41288155267572,
    "lng": 2.0180273428799977,
    "org": "Els Miquels de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "No et perdis el tradicional esmorzar dels Miquels (tiquets a l’Estanc Margarit)."
     },
       {
    "id": 81,
    "titol": "Tronada per anar a buscar el ram de la Geganta",
    "lloc": "Pati de Ca n'Ametller",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "09:30",
    "categoria": "Sant Miquel",
    "icona": "fa-burst",
    "color": "#9dff00",
   "lat": 41.414164,
    "lng": 2.016544,
    "org": "Colla Gegantera de Molins de Rei i Els Miquels de Molins de Rei",
    "fuego": true, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Enmig de traques, trons i músiques de “MúsX”, la geganta Montserrat anirà fins al carrer de Sant Miquel on recollirà de mans dels Miquels de Molins de Rei el ram de flors naturals amb el que l’obsequiaran."
     },
     {
    "id": 82,
    "titol": "Jornada de Portes Obertes al Museu del Renaixement",
   "lloc": "Museu del Renaixement",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "10:00",
    "horaFi": "15:00",
    "categoria": "Museu",
    "icona": "fa-building-columns",
    "color": "#ae560e",
   "lat": 41.412522226165244,
    "lng": 2.0168815964127487,
    "org": "Museu del Renaixement",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc": "El Museu del Renaixement obre gratuïtament per a tothom. Situat al majestuós Palau de Requesens de Molins de Rei, el museu ens convida a conèixer la història de la família Requesens, les característiques principals de l’art del Renaixement i la vida quotidiana al segle XVI. Aprofiteu per venir a descobrir-lo! Audioguia gratuïta disponible en català, castellà i anglès"
  },
      {
    "id": 83,
    "titol": "Tradicional Cercavila dels Gegants Vells",
    "lloc": "Plaça de Catalunya",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "10:30",
    "horaFi": "13:15",
    "categoria": "Sant Miquel",
    "icona": "fa-certificate",
    "color": "#ff007b",
   "lat": 41.413976,
    "lng": 2.015931,
    "org": "Colla Gegantera de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": true, "acc": true, "familia": false, "infantil": false,
    "img": "",
    "desc": "Horari: 10.30 h – Ballada de Gegants davant l’Alcalde. Plaça de la Vila 11.00 h – Tradicional Cercavila dels Gegants Vells 12.45 h – Ballada a la plaça de l’Església"
     },
        {
    "id": 84,
    "titol": "Missa Solemne de Sant Miquel Arcàngel",
    "lloc": "Església Parroquial de Sant Miquel",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "11:00",
    "horaFi": "12:30",
    "categoria": "Sant Miquel",
    "icona": "fa-church",
    "color": "#ff007b",
   "lat": 41.41341957039785,
    "lng": 2.017666878969041,
    "org": "Església Parroquial de Sant Miquel",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": ""
     },
        {
    "id": 85,
    "titol": "Ballada de Sardanes amb la principal del Llobregat",
   "lloc": "Plaça de l'Esglesia",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "12:00",
    "categoria": "Sant Miquel",
    "icona": "fa-certificate",
    "color": "#ff007b",
   "lat": 41.413287,
    "lng": 2.017417,
    "org": "GEA Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "La sardana, com qualsevol altre dels trets de la nostra cultura tradicional, també té el seu lloc dins la nostra Festa Major."
  },
   {
    "id": 86,
    "titol": "Vermut Musical de Sant Miquel a la Pista de la Peni",
    "lloc": "Pati de la Peni",
   "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "12:00",
    "horaFi": "14:00",
    "categoria": "Vermut",
    "icona": "fa-wine-glass",
    "color": "#ff007b",
   "lat": 41.4128388657654,
    "lng": 2.0195345668894986,
    "org": "Joventut Catòlica – La Peni",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Tradicional vermut a la pista d’accés lliure i amb servei de bar i música en directe."
  },
     {
    "id": 87,
    "titol": "Festa dels Miquels",
    "lloc": "Carrer de Sant Miquel",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "12:30",
    "categoria": "Sant Miquel",
    "icona": "fa-superpowers",
    "color": "#ff0073",
   "lat": 41.41288155267572,
    "lng": 2.0180273428799977,
    "org": "Els Miquels de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc": "Festa dels Miquels, amb les nominacions dels Miquel de l’Any 2025 i del Miquel o Miquels més petits. A continuació, el pregó del Miquel de l’Any passat i vermut popular dels Miquels per a tothom."
     },
      {
    "id": 89,
    "titol": "Activitats Infantils",
   "lloc": "Parc de la Mariona",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "17:00",
    "horaFi": "20:30",
    "categoria": "Sant Miquel",
    "icona": "fa-child",
    "color": "#ff0073",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc":"Activitats per als més petits de la casa."
  },
    {
    "id": 90,
    "titol": "A quant va la mel?",
   "lloc": "Parc de la Mariona",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "17:30",
    "horaFi": "19:00",
    "categoria": "Sant Miquel",
    "icona": "fa-masks-theater",
    "color": "#ff0073",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "La Xarxa Molins",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": false,
    "img": "",
    "desc":"Espectacle de jocs amb música en què l’acció se situa fora de l’escenari. Dimonis, formigues, bèsties mitològiques i venedors de mel; cada història té una cançó i cada cançó és un joc que els animadors i músics, vestits d’apicultors, proposen al públic que, jugant, esdevé protagonista de la història. El repertori el componen jocs creats pel grup i es vehiculen a partir de les músiques i cançons de composició pròpia, populars i tradicionals catalanes i d’arreu del món."
  },
   {
    "id": 91,
    "titol": "Havaneres amb Xicranda",
   "lloc": "Parc de la Mariona",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "19:30",
    "horaFi": "20:30",
    "categoria": "Sant Miquel",
    "icona": "fa-certificate",
    "color": "#ff0073",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"Xicranda és un duet format pel Guillem Payaró i Martí Santacana, dos músics formats al Conservatori Superior de Música del Liceu que impulsen una nova mirada a l’havanera catalana. El seu primer treball discogràfic, editat per Picap, recupera i grava per primera vegada composicions inèdites del mestre Josep Maria Roglan, una figura destacada del gènere i autor de “La barca xica”."
  },
  {
    "id": 92,
    "titol": "Final de Festa amb Focs Artificials",
   "lloc": "Parc de la Mariona",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "21:00",
    "horaFi": "21:30",
    "categoria": "Final de Festa",
    "icona": "fa-burst",
    "color": "#ff0073",
   "lat": 41.405304,
    "lng":2.020922,
    "org": "Ajuntament de Molins de Rei",
    "fuego": true, "ruido": false, "aglom": true, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":""
  },
  {
    "id": 93,
    "titol": "Fira d'Atraccions | 2X1",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "19:00",
    "horaFi": "01:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-percent",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"2X1 en totes les atraccions només el divendres 25"
  },
  {
    "id": 94,
    "titol": "Fira d'Atraccions Sense Soroll",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "divendres_25",
    "diaNom": "Divendres 25 de Setembre",
    "dataIso": "2026-09-25",
    "horaInici": "17:00",
    "horaFi": "19:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-volume-xmark",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"Fira Sense Soroll de 17:00 a 19:00 i de 23:00 a 01:00. RECORDA! 2X1 en totes les atraccions només el divendres 25"
  },
  {
    "id": 95,
    "titol": "Fira d'Atraccions",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "19:00",
    "horaFi": "01:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-ticket",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":""
  },
  {
    "id": 96,
    "titol": "Fira d'Atraccions Sense Soroll",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dissabte_26",
    "diaNom": "Dissabte 26 de Setembre",
    "dataIso": "2026-09-26",
    "horaInici": "17:00",
    "horaFi": "19:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-volume-xmark",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"Fira Sense Soroll de 17:00 a 19:00 i de 23:00 a 01:00."
  },
   {
    "id": 97,
    "titol": "Fira d'Atraccions",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "19:00",
    "horaFi": "22:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-ticket",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":""
  },
  {
    "id": 98,
    "titol": "Fira d'Atraccions Sense Soroll",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "diumenge_27",
    "diaNom": "Diumenge 27 de Setembre",
    "dataIso": "2026-09-27",
    "horaInici": "17:00",
    "horaFi": "19:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-volume-xmark",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"Fira Sense Soroll de 17:00 a 19:00."
  },
    {
    "id": 99,
    "titol": "Fira d'Atraccions",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dilluns_28",
    "diaNom": "Dilluns 28 de Setembre",
    "dataIso": "2026-09-28",
    "horaInici": "19:00",
    "horaFi": "01:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-ticket",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":""
  },
  {
    "id": 100,
    "titol": "Fira d'Atraccions Sense Soroll",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dilluns_28",
    "diaNom": "Dilluns 28 de Setembre",
    "dataIso": "2026-09-28",
    "horaInici": "17:00",
    "horaFi": "19:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-volume-xmark",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"Fira Sense Soroll de 17:00 a 19:00 i de 23:00 a 01:00."
  },
  {
     "id": 101,
    "titol": "Fira d'Atraccions",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "19:00",
    "horaFi": "22:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-ticket",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":""
  },
  {
    "id": 102,
    "titol": "Fira d'Atraccions Sense Soroll",
   "lloc": "Avinguda Barcelona (Inici al l'alçada del num. 238)",
    "diaKey": "dimarts_29",
    "diaNom": "Dimarts 29 de Setembre",
    "dataIso": "2026-09-29",
    "horaInici": "17:00",
    "horaFi": "19:00",
    "categoria": "Fira d'Atraccions",
    "icona": "fa-volume-xmark",
    "color": "#ff00ee",
   "lat": 41.40308326249911,
    "lng": 2.02725807274147,
    "org": "Ajuntament de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": true, "infantil": true,
    "img": "",
    "desc":"Fira Sense Soroll de 17:00 a 19:00."
  },
    {
    "id": 103,
    "titol": "Festa per a Adolescents amb DJ Llivina",
   "lloc": "Pati de l'escola El Palau",
    "diaKey": "dissabte_3",
    "diaNom": "Dissabte 3 d'Octubre",
    "dataIso": "2026-10-03",
    "horaInici": "21:30",
    "horaFi": "23:30",
    "categoria": "Només per a adolescents nascuts entre l'any 2009 i 2013",
    "icona": "fa-music",
    "color": "#ff0062",
   "lat": 41.411572,
    "lng": 2.016433,
    "org": "Consell d'Adolescents de Molins de Rei",
    "fuego": false, "ruido": true, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"Cal omplir el formulari d'autorització per aconseguir les polseres identificatives i recollir-les",
    "rsvp":"https://docs.google.com/forms/d/e/1FAIpQLSdpj2fWN7jGwbyDti51kmiWcZYKIg073Ip4WiE2Or8U1uqotA/viewform?pli=1&pli=1s",
  },
  {
    "id": 104,
    "titol": "T-Talent",
   "lloc": "Pati de l'escola El Palau",
    "diaKey": "dissabte_3",
    "diaNom": "Dissabte 3 d'Octubre",
    "dataIso": "2026-10-03",
    "horaInici": "19:00",
    "horaFi": "20:30",
    "categoria": "Només per a adolescents d'entre 12 i 16 anys",
    "icona": "fa-masks-theater",
    "color": "#941313",
   "lat": 41.411572,
    "lng": 2.016433,
    "org": "Consell d'Adolescents de Molins de Rei",
    "fuego": false, "ruido": false, "aglom": false, "acc": false, "familia": false, "infantil": false,
    "img": "",
    "desc":"Guanya fins a 150€!!! Inscriu-te i consulta més informació al botó 'Reservar'",
    "rsvp":"https://molinsderei.cat/concurstalentjove",
  },
  ];
